### ISSUE TITLE
allow TSI that is not 5 or 7 digits to support non land stations

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box-webapp#36]
Can we please allow TSI that is not 5 or 7 digits to support non land stations :

![image](https://github.com/wmo-im/wis2box-webapp/assets/19169339/780e11a4-db89-417d-bcfc-e7319302b502)

**Comment by maaikelimper** [comment]
@david-i-berry can this be closed ?

**Comment by david-i-berry** [comment]
Addressed in #41.
