### ISSUE TITLE
wis2box-webapp station editor blocks the addition of stations with 3-letter names

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box-webapp#42]
From Chems :
when manually adding a station through the interface, if its name consists of only three letters, the system blocks the addition because the name must be longer than three letters. For example, in Morocco and Burkina Faso, we have stations like "ZAG", and I've encountered the same issue.

**Comment by maaikelimper** [comment]
@david-i-berry can this be closed ?

**Comment by david-i-berry** [comment]
Yes, it was addressed a couple of weeks ago in #41.
